import { BudgetConfig } from './types';

export const DEFAULT_BUDGET_CONFIG: BudgetConfig = {
  defaultSessionBudget: 4000,
  mockModeBudget: Number.MAX_SAFE_INTEGER,
  developmentModeBudget: 8000,
  productionModeBudget: 4000,
  maxFreeActionsPerSession: 500,
  maxCheapActionsPerSession: 100,
  maxExpensiveActionsPerSession: 20,
  maxTokensPerMinute: 1500,
  maxTokensPerFiveMinutes: 3000,
  maxApiCallsPerMinute: 5,
  maxApiCallsPerSession: 20,
  warningThreshold: 0.60,
  criticalThreshold: 0.85,
  exhaustedThreshold: 1.00,
  agentBudgets: [
     { agentId: 'nova',   maxTokensPerSession: 2500, maxExpensiveEvents: 12, priority: 1, enabled: true },
     { agentId: 'jinx',   maxTokensPerSession: 1500, maxExpensiveEvents: 8,  priority: 2, enabled: true },
     { agentId: 'default', maxTokensPerSession: 0,   maxExpensiveEvents: 0,  priority: 3, enabled: false }
  ],
  degradationSettings: {
    warningCacheHitTarget: 0.70,
    warningTemplateRate: 0.50,
    warningSkipNonEssential: true,
    criticalUseOnlyTemplates: true,
    criticalUseOnlyFree: false,
    criticalAllowEmergency: true,
    exhaustedUseMock: true,
    exhaustedVisualOnly: false,
    exhaustedAllowAdminOverride: true,
  },
  alertSettings: {
    enabled: true,
    alertOnWarning: true,
    alertOnCritical: true,
    alertOnExhausted: true,
    alertOnEmergencyCutoff: true,
    cooldownMinutes: 15,
  },
  features: {
    enableRateLimiting: true,
    enableBudgetTracking: true,
    enableGracefulDegradation: true,
    enableAdminOverride: true,
    enablePerAgentBudgets: true,
    enableCostLogging: true,
    enableAlerts: true,
    enableRecoveryMode: true,
  },
  version: 1,
  updatedAt: new Date().toISOString(),
  updatedBy: 'system',
};
