export const EMERGENCY_LIMITS = {
  MAX_TOKENS_PER_SESSION: 20000,
  MAX_API_CALLS_PER_SESSION: 50,
  MAX_API_CALLS_PER_MINUTE: 10,
  MAX_TOKENS_PER_MINUTE: 5000,
  MAX_TOKENS_PER_FIVE_MINUTES: 10000,
  MAX_SESSION_DURATION_MINUTES: 120,
  MAX_CONCURRENT_EXPENSIVE_OPS: 3,
  MAX_COST_PER_SESSION_USD: 2.00,
  MAX_COST_PER_DAY_USD: 50.00,
  MAX_COST_PER_HOUR_USD: 10.00,
} as const;
